export const SET_TEAM_LIST = 'SET_TEAM_LIST'

// Event Page
export const REQUEST_EVENT_INFO = 'REQUEST_EVENT_INFO'
export const RECEIVE_EVENT_INFO = 'RECEIVE_EVENT_INFO'
export const REQUEST_EVENT_TEAMS = 'REQUEST_EVENT_TEAMS'
export const RECEIVE_EVENT_TEAMS = 'RECEIVE_EVENT_TEAMS'

// Team Page
export const REQUEST_TEAM_INFO = 'REQUEST_TEAM_INFO'
export const RECEIVE_TEAM_INFO = 'RECEIVE_TEAM_INFO'
export const REQUEST_TEAM_YEAR_EVENTS = 'REQUEST_TEAM_YEAR_EVENTS'
export const RECEIVE_TEAM_YEAR_EVENTS = 'RECEIVE_TEAM_YEAR_EVENTS'
