// AppBar / Nav Drawer
export const INCREMENT_LOADING_COUNT = 'INCREMENT_LOADING_COUNT'
export const DECREMENT_LOADING_COUNT = 'DECREMENT_LOADING_COUNT'

export const TOGGLE_OFFLINE = 'TOGGLE_OFFLINE'

export const SET_BOTTOM_NAV_VALUE = 'SET_BOTTOM_NAV_VALUE'

// Resetting Page
export const RESET_PAGE = 'RESET_PAGE'

// Set page state
export const SET_PAGE_STATE = 'SET_PAGE_STATE'

// Snackbars
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

// Event Page
export const RECEIVE_EVENT_INFO = 'RECEIVE_EVENT_INFO'
export const RECEIVE_EVENT_MATCHES = 'RECEIVE_EVENT_MATCHES'
export const RECEIVE_EVENT_TEAMS = 'RECEIVE_EVENT_TEAMS'

// Event List Page
export const RECEIVE_YEAR_EVENTS = 'RECEIVE_YEAR_EVENTS'

// Team Page
export const RECEIVE_TEAM_INFO = 'RECEIVE_TEAM_INFO'
export const RECEIVE_TEAM_YEAR_EVENTS = 'RECEIVE_TEAM_YEAR_EVENTS'
export const RECEIVE_TEAM_YEAR_MATCHES = 'RECEIVE_TEAM_YEAR_MATCHES'

// Event List Page
export const RECEIVE_TEAM_LIST_PAGE = 'RECEIVE_TEAM_LIST_PAGE'

// Match Page
export const RECEIVE_MATCH_INFO = 'RECEIVE_MATCH_INFO'

